### ISSUE TITLE
pos_in_grid not set for vertical/horizontal modes

### ISSUE THREAD

**Issue by steellynx** [m42e/dd2vtt-stick#2]
When using "-y" or "-x" I get the following error:
```python
$ stick.py -y -o all.dd2vtt a.dd2vtt b.dd2vtt
INFO:__main__:Created canvas with size of 1152 x 1536
Traceback (most recent call last):
  File "stick.py", line 239, in <module>
    main()
  File "stick.py", line 234, in main
    c = Canvas(files, mode, image_type=image_type, size_mode=size_mode)
  File "stick.py", line 69, in __init__
    self.transform_information()
  File "stick.py", line 170, in transform_information
    z["x"] += f["pos_in_grid"]["x"]
KeyError: 'pos_in_grid'
```

It works perfectly with "-g" :-)

I'm a little pressed with time this week, but I have an idea for refactoring `create_canvas(...)` to use horizontal/vertical modes to define a grid and therefor only have one place where things are stitched together. If you want I can (try to) create a pull request?

**Comment by m42e** [comment]
Fell free to create a pr! Thanks, I haven‘t been using it for a while as I have my things prepared upfront. I would be happy to merge your PR.
